alter table public.sanmeigaku_diagnoses
  add column if not exists gender text null,
  add column if not exists calculation_version text null,
  add column if not exists calculation_result jsonb null,
  add column if not exists updated_at timestamptz null;

comment on column public.sanmeigaku_diagnoses.gender is
  'Optional customer-provided gender. Not used by fixed-mvp-v1 calculations.';

comment on column public.sanmeigaku_diagnoses.calculation_version is
  'Version identifier of the diagnosis calculation implementation.';

comment on column public.sanmeigaku_diagnoses.calculation_result is
  'Structured result generated by the versioned diagnosis calculation.';

comment on column public.sanmeigaku_diagnoses.updated_at is
  'Last update time. Existing rows remain null.';
